### ISSUE TITLE
LSP doesn't recognise virtual environment

### ISSUE THREAD

**Issue by fast-90** [zbelial/lspce#6] opened 2023-07-01 08:48 UTC
I am trying to use this with [pylsp](https://github.com/python-lsp/python-lsp-server), and LSP is working since flymake is providing error diagnostics. However, it seems that it doesn't recognise my virtual environment (Eglot was able to recognise the virtual environment with my setup, see below).

Is there a way to configure it so that it recognises the virtual environment? How have you set this up for yourself?

For reference, my setup is:
- Python LSP server installed globally (not in the virtual environment)
- Virtual environment is in a `.venv` folder, which is located in the project folder.
- I use `pyvenv` to activate the the correct virtual environment.

Please let me know if I need to provide any further information. This looks cool and I'm excited to try it out!

**Comment by zbelial** [comment] 2023-07-01 10:28
I haven't used lspce with virtual environment, actually I have never used python's virtual environment. I'll first learn how to use it and then try to answer your question. 

Thanks for giving lspce a try.

**Comment by fast-90** [comment] 2023-07-01 11:13
Alright, will have a close look on this one! I don't think my Elisp coding skills and LSP understanding is good enough to help with the code, but if I can help in any other way please let me know.

**Comment by zbelial** [comment] 2023-07-01 11:26
Thanks. 
If you have any other sugguestions/problems, feel free to create issues. Thanks in advance.

**Comment by zbelial** [comment] 2023-07-27 08:42
Hi @fast-90 
Sorry for late feedback, I finally found time to try to solve this problem, and I guess I have some progress now.

I pushed a new branch `virtualenv`, where lspce supports `workspace/didChangeConfiguration` notification. Using this new feature, lspce can send some workspace configuration (read from .dir-locals.el) to lsp servers (very similar to what eglot does, actually I learnt this from eglot).  

Then I did some test. The following is what I did:
1. Create a new project `~/tmp/venv`
```
mkdir -p ~/tmp/venv && cd ~/tmp/venv/ && git init .
```
2. Create a new virtual environment in this new project's directory
```
python -m venv .venv
```
3. Activate the virtualenv
```
source .venv/bin/activate
```
4. Install some python packages using pip
```
pip install baostock -i https://pypi.tuna.tsinghua.edu.cn/simple/ --trusted-host pypi.tuna.tsinghua.edu.cn
```
5. Create .dir-locals.el and fill it with
```elisp
((python-mode
  . ((lspce-workspace-configuration
      . (:pylsp (:plugins (:jedi_completion (:include_params t
                                             :fuzzy t)
                           :jedi (:environment "/home/lucency/tmp/venv/.venv/bin/python")
                           :pylint (:enabled :json-false)))))
     (indent-tabs-mode . nil)))
 (python-ts-mode
  . ((lspce-workspace-configuration
      . (:pylsp (:plugins (:jedi_completion (:include_params t
                                             :fuzzy t)
                           :jedi (:environment "/home/lucency/tmp/venv/.venv/bin/python")
                           :pylint (:enabled :json-false)))))
     (indent-tabs-mode . nil))))
```
6. Create a new python file bs.py
```python
import baostock as bs
import pandas as pd

#### 登陆系统 ####
lg = bs.login()
# 显示登陆返回信息
print('login respond error_code:'+lg.error_code)
print('login respond  error_msg:'+lg.error_msg)
```
7. Open bs.py in Emacs and enable `lspce-mode`
When I inputted "bs.", completion poped up, and since I only installed baostock in this virtualenv but not the system, I guessed lspce recognised virtualenv now. 


Is this what you wanted?  If not, what did you want actually?

**Comment by alkurbatov** [comment] 2024-07-02 07:46
Hey @zbelial I experience the same problems on my mac with Python projects. I also use local .venv (i.e. .venv folder suited inside the project's folder).
So far it seems that the config you suggested solves the issue. Here is my setup:

```elisp
((python-ts-mode
  (lspce-workspace-configuration .
      (:pylsp (:plugins (:jedi_completion (:include_params t :fuzzy t)
                         :jedi (:environment "/<path-to-project>/.venv/bin/python")
                         :flake8 (:enabled :json-false)
                         :rope_completion (:enabled :json-true)))))))
```

**Comment by zbelial** [comment] 2024-07-04 11:57
Hi @alkurbatov , thanks for letting me know that the branch `virtualenv` works. I've not merged this branch into master because of no response(also because I don't write python), but now I think I can merge :) Thanks again.
BTW I stole the idea from eglot. Thank you, eglot.

**Comment by alkurbatov** [comment] 2024-07-04 12:06
Sorry, I haven't tested the particular branch. It works with the master and the config described above.  
I can retest with the branch if needed.

**Comment by alkurbatov** [comment] 2024-07-04 12:50
> It's wired. The master branch doesn't have `lspce-workspace-configuration`, so maybe something happens somewhere else and makes it work. Can you confirm that without the above config, it doesn't work? Thanks.

I confirm that it doesn't work without lspce-workspace-configuration and `:jedi (:environment` in the master branch. I can't inspect imports and autocompletion doesn't see data from venv.
Although after your comment it looks weird that the setting helps.

**Comment by alkurbatov** [comment] 2024-07-04 12:54
I'll doublecheck with the virtualenv branch just in case.

**Comment by zbelial** [comment] 2024-07-04 13:02
> 'll doublecheck with the virtualenv branch just in case.

Thanks @alkurbatov .

**Comment by zbelial** [comment] 2024-07-04 13:58
Thanks a lot!

> Some times it works, but often don't. This error not happens in the master branch as I can't simply jump into the problematic string.

Maybe it's because virtualenv branch is out of sync with master ( just a guess though), I'll merge master with it.  

I'm not sure why `redisplay` errors happen, I think I'll test it first, when it works, I'll let you know, then you can give it another try.

**Comment by zbelial** [comment] 2024-07-05 13:23
Hi @alkurbatov , before digging into the problem, I need to know some things about how did you test the virtualenv branch, thanks. 
1. Which platform were you using lspce on? Linux, macOS or Windows? 
2. After switching to the `virtualenv` branch, did you rebuild the lspce module ?
3. Were you using EMacs in a terminal?

**Comment by alkurbatov** [comment] 2024-07-05 13:45
Hi @zbelial 

1. macOS
2. Yes, and I completely removed all the previous artifacts including source code.
3. Yes.

**Comment by zbelial** [comment] 2024-07-06 14:18
I tested again in Konsole on Linux in almost the same steps quoted below, but had no luck to reproduce what you had.  I also installed python-poetry, poetry.el and pyvenv.el but haven't had time to test with them (unfamiliar with them since I'm not a python programmer).  Could you give a recipe to reproduce the issue please? 

An image showing what I got when testing
![图片](https://github.com/zbelial/lspce/assets/6436456/0f26a5e2-d02e-4cfa-a534-e5b3bc6d7911)


> Hi @fast-90 Sorry for late feedback, I finally found time to try to solve this problem, and I guess I have some progress now.
> 
> I pushed a new branch `virtualenv`, where lspce supports `workspace/didChangeConfiguration` notification. Using this new feature, lspce can send some workspace configuration (read from .dir-locals.el) to lsp servers (very similar to what eglot does, actually I learnt this from eglot).
> 
> Then I did some test. The following is what I did:
> 
>     1. Create a new project `~/tmp/venv`
> 
> 
> ```
> mkdir -p ~/tmp/venv && cd ~/tmp/venv/ && git init .
> ```
> 
>     2. Create a new virtual environment in this new project's directory
> 
> 
> ```
> python -m venv .venv
> ```
> 
>     3. Activate the virtualenv
> 
> 
> ```
> source .venv/bin/activate
> ```
> 
>     4. Install some python packages using pip
> 
> 
> ```
> pip install baostock -i https://pypi.tuna.tsinghua.edu.cn/simple/ --trusted-host pypi.tuna.tsinghua.edu.cn
> ```
> 
>     5. Create .dir-locals.el and fill it with
> 
> 
> ```emacs-lisp
> ((python-mode
>   . ((lspce-workspace-configuration
>       . (:pylsp (:plugins (:jedi_completion (:include_params t
>                                              :fuzzy t)
>                            :jedi (:environment "/home/lucency/tmp/venv/.venv/bin/python")
>                            :pylint (:enabled :json-false)))))
>      (indent-tabs-mode . nil)))
>  (python-ts-mode
>   . ((lspce-workspace-configuration
>       . (:pylsp (:plugins (:jedi_completion (:include_params t
>                                              :fuzzy t)
>                            :jedi (:environment "/home/lucency/tmp/venv/.venv/bin/python")
>                            :pylint (:enabled :json-false)))))
>      (indent-tabs-mode . nil))))
> ```
> 
>     6. Create a new python file bs.py
> 
> 
> ```python
> import baostock as bs
> import pandas as pd
> 
> #### 登陆系统 ####
> lg = bs.login()
> # 显示登陆返回信息
> print('login respond error_code:'+lg.error_code)
> print('login respond  error_msg:'+lg.error_msg)
> ```
> 
>     7. Open bs.py in Emacs and enable `lspce-mode`
>        When I inputted "bs.", completion poped up, and since I only installed baostock in this virtualenv but not the system, I guessed lspce recognised virtualenv now.
> 
> 
> Is this what you wanted? If not, what did you want actually?

**Comment by alkurbatov** [comment] 2024-07-06 16:07
The issues listed above happen not during autocompletion, but when I click `M-.` on particular import. 

E.g. the issue on my screenshot was found when I clicked `M-.` on `SIGTERM` in:
```python
from signal import SIGTERM
```
No poetry or venv need as `signal` is builtin module.

**Comment by alkurbatov** [comment] 2024-07-06 16:08
The issues listed above happen not during autocompletion, but when I click `M-.` on particular import. 

E.g. the issue on my screenshot was found when I clicked `M-.` on `SIGTERM` in:
```python
from signal import SIGTERM
```
No poetry or venv need as `signal` is builtin module.

**Comment by zbelial** [comment] 2024-07-06 17:52
Unfrotunately still no luck to reproduce your problem. I created a simple project with only one python file, and there was only a line of code  `from signal import SIGTERM`.  
But I had another problem, `M-.` couldn't find SIGTERM's definition. I'm not sure what should be blamed, lspce or pylsp (pyright worked well though).  And I didn't have any errors about redisplay. 
Sorry for not making any progress, but I don't know what I can do now.

**Comment by alkurbatov** [comment] 2024-07-06 20:23
> But I had another problem, M-. couldn't find SIGTERM's definition.

Yeah we have slightly different behaviors:
- in the main branch `M-.` cannot be used on SIGTERM and on some other modules.
- in the virtualenv branch I can press `M-.` on SIGTERM but usually it fails.

I believe that since we have such difference something in the virtualenv branch works better.

**Comment by alkurbatov** [comment] 2024-07-06 20:49
I think we should reduce the variance to make things simpler. @zbelial could you please merge the virtualenv branch?

**Comment by zbelial** [comment] 2024-07-07 02:21
I just created a new branch `master-virtualenv`, which was based on master, and I have merged the `virtualenv` branch into it.

**Comment by alkurbatov** [comment] 2024-07-07 11:03
Ok, so what I have now:

WIth the `master-virtualenv` branch and your code example:

a. Attempt to press `M-.` on `SIGTERM` in `from signal import SIGTERM` produce `user-error: No definitions found for: SIGTERM` in the Warnings buffer. No other side effects.

b. Attempt to get autocompletion in imports (e.g. type `from pandas import D` and press TAB) doesn't work.

c. Attempt to call autocompletion on methods (e.g. type `lg = bs.login()` and on next line `lg.` and press TAB) doesn't work.

Tested on Emacs 30 and Python 3.11 and 3.12 with poetry and your pylsp config.

However, on my other more complex Python project autocomplete features work with some modules. Probably this is pylsp issue on mac? No idea.

**Comment by alkurbatov** [comment] 2024-07-07 11:12
For comparison I tried pyright, but seems that this is another difficult quest :)
https://github.com/zbelial/lspce/issues/40

**Comment by zbelial** [comment] 2024-07-07 11:19
> Ok, so what I have now:
> 
> With the `master-virtualenv` branch and your code example:
> 
> a. Attempt to press `M-.` on `SIGTERM` in `from signal import SIGTERM` produce `user-error: No definitions found for: SIGTERM` in the Warnings buffer. No other side effects.

Maybe pylsp has some problems in this case. I'm not sure.

> b. Attempt to get autocompletion in imports (e.g. type `from pandas import D` and press TAB) doesn't work.

What do you bind TAB to?  Here after typing `from pandas import D` and then calling `completion-at-point`(bound to C-M-i) worked. 

> c. Attempt to call autocompletion on methods (e.g. type `lg = bs.login()` and on next line `lg.` and press TAB) doesn't work.

Worked too for me (after `lg.`, completion menu appeared automatically, no need to press TAB) 

> Tested on Emacs 30 and Python 3.11 and 3.12 with poetry and your pylsp config.
> 
> However, on my other more complex Python project autocomplete features work with some modules. Probably this is pylsp issue on mac? No idea.

**Comment by alkurbatov** [comment] 2024-07-07 11:44
Ok, so now I can confirm that lspce works well with pyright and everything can be resolved and stepped in. So y guess is that pylsp doesn't play nice on macOS.

**Comment by zbelial** [comment] 2024-07-07 11:51
Great! But I think `virtualenv` needs to be improved (I learnt more knowledge about lsp configuration :) ) and then It can be merged with master.

**Comment by alkurbatov** [comment] 2024-07-07 11:52
> What do you bind TAB to?

```elisp
(define-key company-mode-map [remap indent-for-tab-command]
            #'company-indent-or-complete-common)

;; Enable indentation+completion using the TAB key.
;; completion-at-point is often bound to M-TAB.
(setq tab-always-indent 'complete)
```

I tried TAB, M-TAB and direct call to `completion-at-point` - no effect. Popup don't upper too.

**Comment by zbelial** [comment] 2024-07-07 11:56
> > What do you bind TAB to?
> 
> ```emacs-lisp
> (define-key company-mode-map [remap indent-for-tab-command]
>             #'company-indent-or-complete-common)
> 
> ;; Enable indentation+completion using the TAB key.
> ;; completion-at-point is often bound to M-TAB.
> (setq tab-always-indent 'complete)
> ```
> 
> I tried TAB, M-TAB and direct call to `completion-at-point` - no effect. Popup don't appear too.

I don't think I can solve this problem ATM. Let's just keep this issue open, maybe other guys will tell us what the problem is.

**Comment by alkurbatov** [comment] 2024-07-12 09:34
I think I found out why it doesn't work with the master-virtualenv branch. The issue was on my side: the venv wasn't activated properly. So in short: it would be better to merge master-virtualenv (or some parts of it) into master to make scenarios like #a work.


Currently I have several behaviors:
a. When I activate venv and call Emacs from the same terminal, everything works well with pylsp even without the config (might be because pylsp runs in the same venv).

b. When I call Emacs from UI, autocompletion and "jump into module" doesn't work with or without lspce-workspace-configuration setting.

c. When I call Emacs from terminal without venv activation, it behaves the same as in #b.

d. If I use the current master branch,  #a doesn't work.


Speaking about the desired behavior: usually people expect that LSP will handle venv for them without manual activation of anything.
To achieve it one should:
- specify path to venv in some config (see (e.g. like In this issue https://github.com/zbelial/lspce/issues/41)
- use one of Emacs packages (e.g. pyvenv). These packages does preliminary venv activation and sometimes overload internal functions related to search of Python binary and it's libraries.

**Comment by alkurbatov** [comment] 2024-07-12 09:35
I think I found out why it doesn't work with the master-virtualenv branch. The issue was on my side: the venv wasn't activated properly. So in short: it would be better to merge master-virtualenv (or some parts of it) into master to make scenarios like #a work.


Currently I have several behaviors:
a. When I activate venv and call Emacs from the same terminal, everything works well with pylsp even without the config (might be because pylsp runs in the same venv).

b. When I call Emacs from UI, autocompletion and "jump into module" doesn't work with or without lspce-workspace-configuration setting.

c. When I call Emacs from terminal without venv activation, it behaves the same as in #b.

d. If I use the current master branch,  #a doesn't work.


Speaking about the desired behavior: usually people expect that LSP will handle venv for them without manual activation of anything.
To achieve it one should:
- specify path to venv in some config (see (e.g. like In this issue https://github.com/zbelial/lspce/issues/41)
- use one of Emacs packages (e.g. pyvenv). These packages does preliminary venv activation and sometimes overload internal functions related to search of Python binary and it's libraries.

**Comment by alkurbatov** [comment] 2024-07-12 14:25
> BTW, since I'm not familiar with python and tools around it, if you'd like to contribute in this aspect, it'd be greet. :)

That could be hard as I am not familiar with Rust and barely know Elisp. I'll try to inspect the code first.

**Comment by zbelial** [comment] 2024-07-13 01:51
Hi, that's ok, don't worry. I'll try to solve the issue, but I guess it may need some time though.

**Comment by zbelial** [comment] 2024-07-13 12:07
Hi @alkurbatov , I just got virtualenv work in lspce (only worked with pylsp and jedi-language-server, but not pyright-langserver ATM). This new method doese not depend on pyvenv or anything similar, but just a `.dir-locals.el`. 

The following is what I did (using master branch): 
0. create an virtual env at the root of a project ( e.g. .venv )  (similar to what I described in this [comment](https://github.com/zbelial/lspce/issues/6#issuecomment-1653168207))
1. create a `.dir-locals.el` at the root of the project
```elisp
((python-mode
  . ((eval . (progn
               (setq-local lspce-jedi-environment "/home/lucency/tmp/venv/.venv/bin/python")))))
 (python-ts-mode
  . ((eval . (progn
               (setq-local lspce-jedi-environment "/home/lucency/tmp/venv/.venv/bin/python"))))))
```
2. define a initializationOption function for pylsp
```elisp
(defun lspce-pylsp-initializationOptions ()
  (let ((options (make-hash-table :test #'equal)))
    (lspce--add-option "pylsp.plugins.jedi_completion.include_params" t options)
    (lspce--add-option "pylsp.plugins.jedi_completion.fuzzy" t options)
    (when (boundp 'lspce-jedi-environment)
      (lspce--add-option "pylsp.plugins.jedi.environment" lspce-jedi-environment options))
    (lspce--add-option "pylsp.plugins.pylint.enabled" :json-false options)
    options))
```
3. config `lspce-server-programs`
```elisp
(setq lspce-server-programs `(("python" "pylsp" "" lspce-pylsp-initializationOptions)))
```
4. enable `lspce-mode` in the buffers of this project, pylsp should work


This method does not work for pyright though. I have no idea why.  

If this works for you too, I'd like to close this issue.  There are so many different ways to support virtualenv in Python world, and I've spent too much time on this.

**Comment by zbelial** [comment] 2024-07-13 13:47
Some notes about pyright.  
A pyright developer said pyright will read pyrightconfig.json at the root of a project automatically, but it doesn't work for me. Its documentation says you can set python.pythonPath in settings and it will firgure out the environment, but unfortunately it doesn't work for me too.  Maybe it's all my fault, I don't know.  And maybe some day I'll continue to add support for pyright working with virtualenv.  Now let's just call it an end.

**Comment by alkurbatov** [comment] 2024-07-13 13:52
> Its documentation says you can set python.pythonPath in settings and it will firgure out the environment, but unfortunately it doesn't work for me too. 

I also tried this and it didn't work. Pretty sure this is about VSCode config, not pyright.

> only worked with pylsp and jedi-language-server, but not pyright-langserver ATM

I bet this is because of the way pyright identifies venvs. According to the docs, pyright uses the current available python interpreter to calculate path to venv. This is why they suggest to set pythonPath via VSCode.

**Comment by alkurbatov** [comment] 2024-07-13 14:11
> If this works for you too, I'd like to close this issue. There are so many different ways to support virtualenv in Python world, and I've spent too much time on this.

Tested:
- Worked if I do preliminary venv activation in the terminal.
- It didn't work without manual venv activation or with GUI version of Emacs.

I think we have some differences in the setups that cause confusion:
- My usual setup with pylsp is a separate venv created by pipx (i.e. `pipx install python-lsp-server`). With it I had all the results described above.
- Just in case I tested your suggestion with the pylsp from homebrew (i.e. `brew install pthon-lsp-server`), but it worked exactly the same.

My guess:
- On Linux pylsp is set up in a different way, if you install it using package manager. Probably you should try to install pylsp with pipx.
- There is some difference in a way venv activated. I have a feeling that this jedi setting doesn't help at all. Probably you use jedi language server?

Anyways I am more interested in pyright as pylsp has several weird bugs which are blockers to me :(

**Comment by zbelial** [comment] 2024-07-13 14:45
> > If this works for you too, I'd like to close this issue. There are so many different ways to support virtualenv in Python world, and I've spent too much time on this.
> 
> Tested:
> 
>     * Worked if I do preliminary venv activation in the terminal.
> 
>     * It didn't work without manual venv activation or with GUI version of Emacs.

I should have mentioned that I didn't activate venv at all.  Just used the .dir-locals.el file, It worked well in my test project. 
Let me summary.

1. Created a new project ~/tmp/venv

2.  Created a new virtual environment in this new project's directory

3. Activated the virtualenv to install some python packages only in this virtual env.

All the above happened in terminal. Now this project had been prepared.  Then I  started Emacs in GUI mode, created `.dir-locals.el` and opened a new file `bs.py`, and input all the code mentioned above.   Code completion, jumping to definitions all worked well. 


> 
> I think we have some differences in the setups that cause confusion:
> 
>     * My usual setup with pylsp is a separate venv created by pipx (i.e. `pipx install python-lsp-server`). With it I had all the results described above.
> 
>     * Just in case I tested your suggestion with the pylsp from homebrew (i.e. `brew install python-lsp-server`), but it worked exactly the same.
> 
> 
> My guess:
> 
>     * On Linux pylsp is set up in a different way, if you install it using package manager. Probably you should try to install pylsp with pipx.
> 
>     * There is some difference in a way venv activated. I have a feeling that this jedi setting doesn't help at all. Probably you use jedi language server?
> 
> 
> Anyways I am more interested in pyright as pylsp has several weird bugs which are blockers to me :(

Yes, in the above comment, I used pylsp installed from Manjaro's repos, but I just uninstalled it and reinstalled using pipx, it workd too.  

All in all, as I mentioned, there are different ways to activate venv in Emacs, I don't want to add support for all, so I chose the way to use `.dir-locals.el` only. No need to activate venv at all. 

Since pyright keeps only vscode in mind, I'd like to delete code about it from lspce actually. Sorry.

**Comment by zbelial** [comment] 2024-07-13 14:47
BTW, I tried pyvenv.el, and I think it enables a venv globally in Emacs, right? It's not flexible at all IMHO.  But I might be wrong since I'm not familar with it.

**Comment by alkurbatov** [comment] 2024-07-13 14:53
> I should have mentioned that I didn't activate venv at all. 

In this case the suggested approach didn't work for me.

> Since pyright keeps only vscode in mind,

I don't think they do, but VSCode is very popular. There should be the way to specify Python path somehow.

>  I'd like to delete code about it from lspce actually. Sorry.

I would suggest to burrow ideas from eglot as it works well with pyright.

> BTW, I tried pyvenv.el, and I think it enables a venv globally in Emacs, right? It's not flexible at all IMHO. But I might be wrong since I'm not familar with it.

Me too, but I think you're right. They patch internals a lot.

**Comment by zbelial** [comment] 2024-07-13 15:34
> > I should have mentioned that I didn't activate venv at all.
> 
> In this case the suggested approach didn't work for me.

sadly.

> 
> > Since pyright keeps only vscode in mind,
> 
> I don't think they do, but VSCode is very popular. There should be the way to specify Python path somehow.

At least a developer said in an issue before. I'm pretty sure about this. Maybe they have changed their mind now. 

> 
> > I'd like to delete code about it from lspce actually. Sorry.
> 
> I would suggest to burrow ideas from eglot as it works well with pyright.
> 

Maybe some day. Actually I have tested pyright with eglot, it worked if I activated the venv before enabling eglot, otherwise it didn't work too.

**Comment by alkurbatov** [comment] 2024-07-13 15:39
> Actually I have tested pyright with eglot, it worked if I activated the venv before enabling eglot, otherwise it didn't work too.

With eglot I know two ways to make automatic activation of venv with pyright:
1. Create .venv in the root of the project (no config required).
2. Write pyright config like it was described here: https://github.com/zbelial/lspce/issues/41

I think that the issue with pyright not read config by unknown reason is what blocks it's support.

**Comment by zbelial** [comment] 2024-07-14 00:14
Just captured what I did to make the test. 


https://github.com/user-attachments/assets/4a07fcfd-947a-4ee1-8d89-31f836db28e4

**Comment by zbelial** [comment] 2024-07-14 04:13
I also made pyright work with venv, but I'm not sure it's good enough or not.  What you need is `.dir-locals.el` too. Like the following:
```elisp
((python-mode
  . ((eval . (progn
               (setq-local exec-path (append (list "/home/XXXX/tmp/venv/.venv/bin/") exec-path))
               (setq-local process-environment (copy-sequence process-environment))
               (setq-local lspce-inherit-exec-path t)))))
 (python-ts-mode
  . ((eval . (progn
               (setq-local exec-path (append (list "/home/XXXX/tmp/venv/.venv/bin/") exec-path))
               (setq-local process-environment (copy-sequence process-environment))
               (setq-local lspce-inherit-exec-path t))))))
```

In this way, pyright can find the python interpreter in the venv.

**Comment by zbelial** [comment] 2024-07-20 03:17
Hi @alkurbatov , does the `.dir-locals.el` work for you now? If not, could you please provide a step-by-step reproducible recipe? Or I'll close this issue ( and #41 ).  But since I use Linux, even you provide a recipe, I couldn't promise to reproduce your problem.

**Comment by zbelial** [comment] 2024-07-22 14:54
> I am unsure whether I should post my issue here or create a new one instead. The problem I am facing is about the compatibility with [direnv](https://github.com/wbolster/emacs-direnv).
> 
> Basically it provides a separate development environment within a specific directory, such as binaries and environment variables. By utilizing integration packages, Emacs or shells can automatically load the corresponding development environment if it is under the directory. I am now using it for rust development, so that different projects can have different rust versions.
> 
> With the help of `dir-locals` and `lspce-inherit-exec-path`, `lspce` can be started successfully, but `rust-analyzer` can not be compiled successfully, as indicated in the following log:
> 
> ```
> The system library `openssl` required by crate `openssl-sys` was not found.
> 
> [stderr]   The file `openssl.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
> 
> [stderr]   The PKG_CONFIG_PATH environment variable is not set.
> ```
> 
> As per the log, the problem seems to be that `lspce` is unable to recognize the environment variables provided by `direnv`. Do you have any suggestions on how to resolve this issue? I can also provide steps for reproducing the problem if you want.

Hi @WeissP, I guess it's because lspce only handles PATH now(actually I've thought about implementing this feature in a more general way so lspce can handle any environment variables but I was too lazy to implement it, haha), so other environment variables do not work as expected. 
Also It'll be great if you could provide steps about how to reproduce the problem so when I make a fix, I can make use of your reproducing recipe, but there's no hush. 

And I'm a little busy these days, so I'm not sure when I can fix this problem. This weekend or maybe till next weekend, I could not promise.

**Comment by WeissP** [comment] 2024-07-23 07:58
Hi, thanks for the quick reply. I guess using [current_dir](https://doc.rust-lang.org/std/process/struct.Command.html#method.current_dir) could be helpful. 
Regarding steps for reproducing, it turned out that my approach involves a bunch of packages you will have to install (nix + nix-direnv + devshell + emacs-direnv), and I am also not sure about potential conflicts with your global Rust ecosystem (which make it harder to debug and test). 

So I guess if it is possible to make `pyvenv` work without passing only environment variable `PATH` but by forwarding all environments under a user specified directory, my issue could also be solved. I am willing to test this in my own environment.

If you are still interested in reproducing and testing the issue yourself, I am more than willing to provide you with detailed instructions :).

**Comment by WeissP** [comment] 2024-07-23 14:08
> how to decide which environemnt variables should be passed to lspce to start the lsp server?

IMO it would be super hard (if not impossible) to determine what variables should be passed to `lspce` generally, as each project has its own dependencies. What I would try to do is to pass all environment variables under the project directory to `lspce`. 

I would be surprised if `current_dir` doesn't work. In fact, when I start emacs in the project directory, `lspce` works perfectly.

**Comment by zbelial** [comment] 2024-07-23 14:19
> all environment variables under the project directory
How can lspce get all environtment variables then? 

> 
> I would be surprised if `current_dir` doesn't work. In fact, when I start emacs in the project directory, `lspce` works perfectly.
You mean you start emacs in th the project directory from a shell, right? I think in this case emacs can inherit environtment variables from the shell, so lspce works well.  This is different with how I did the test, but I forgot what I did. 

Anyway, in my mind, I think we can specify which env variables. e.g. in a .dir-locals.el, all these env variables can be passed lspce then. Can this way solve your issue?

**Comment by WeissP** [comment] 2024-07-23 14:29
> Anyway, in my mind, I think we can specify which env variables. e.g. in a .dir-locals.el, all these env variables can be passed lspce then. Can this way solve your issue?

Yes, it is possible, but I would need to define all specific environment variables twice - once in the virtual environment configuration and once in dir-locals for all projects.

**Comment by zbelial** [comment] 2024-07-23 14:37
> > Anyway, in my mind, I think we can specify which env variables. e.g. in a .dir-locals.el, all these env variables can be passed lspce then. Can this way solve your issue?
> 
> Yes, it is possible, but I would need to define all specific environment variables twice - once in the virtual environment configuration and once in dir-locals for all projects.


Sorry that in my last comment,  one sentence was quoted incorrectly.  

> all environment variables under the project directory

How can lspce get all environtment variables then?  

I don't know how can lspce achieve this. Even it can, maybe it's unneccesary to pass all.

**Comment by WeissP** [comment] 2024-07-23 14:48
> How can lspce get all environtment variables then?

So far I have two ideas in mind:
1. Simply start the server instance within the project directory, and the virtual environment will (probably, hopefully) handle it correctly.
2. If the first approach doesn't work well, at least `direnv` will generate `env.bash` file that includes all specified environment variables internally. If user can specify a file path to let the process load before it starts the lsp server, it might also resolve the issue.

**Comment by zbelial** [comment] 2024-07-23 14:50
> but I would need to define all specific environment variables twice

I think you don't have to define them twice though, in lspce, you just specify which one(s) should be passed.  Maybe we can use a elisp lisp variable to do this.  e.g. `(setq vars '("ENV1" "ENV2"))`.

**Comment by zbelial** [comment] 2024-07-23 14:51
> > How can lspce get all environtment variables then?
> 
> So far I have two ideas in mind:
> 
>     1. Simply start the server instance within the project directory, and the virtual environment will (probably, hopefully) handle it correctly.
> 
>     2. If the first approach doesn't work well, at least `direnv` will generate `env.bash` file that includes all specified environment variables internally. If user can specify a file path to let the process load before it starts the lsp server, it might also resolve the issue.

I think 2 is better, but I think I should learn more about direnv before making any decision.

**Comment by WeissP** [comment] 2024-07-23 15:01
> I think 2 is better, but I think I should learn more about direnv before making any decision.

Best of luck! While I'm not an expert on `direnv`, I am still willing to offer assistance if needed.

**Comment by zbelial** [comment] 2024-07-27 05:04
Hi @WeissP , I pushed a new branch `envs`, you can use it to pass multiple environment variables to lspce's rust code side. But you still need to rely on `.dis-locals.el`. I explained the reason in README ( also attached below ).

```org
   Sometime, you may need to pass some environment variables to rust code so that lspce can use these environment variables to start lsp server processes. You can use =lspce-envs-pass-to-subprocess= then, which is a list of environment variables, and the values of these environment variables are retrieved from =process-environment=, except ~PATH~, which is from =exec-path=. 

   The reason why this feature works in this way is I don't want lspce to be tightly bound with other tools, such as direnv, python's venv, and so on. So you should use someway to populate =process-environment= first if you want to use this feature.
   
   =lspce-envs-pass-to-subprocess= has made =lspce-inherit-exec-path= obsolete, even you can still use it. The logic is: all environment variables will be passed, and if =lspce-inherit-exec-path= is set true, PATH will be passed too.
```

What do you think?

**Comment by WeissP** [comment] 2024-07-27 09:07
Hi, thanks for the update. But so far I can't find the branch `envs` for some reason.

I am also agree with you that `lspce` shouldn't be bound tightly with other tools. However, regarding the ideas I previously mentioned, I don't think they are specific to `direnv`. What are your thoughts on them?

If you don't have time to implement them at the moment, I am also willing to contribute and work on them, if you would like.

**Comment by zbelial** [comment] 2024-07-27 09:56
> Hi, thanks for the update. But so far I can't find the branch `envs` for some reason.
> 
> I am also agree with you that `lspce` shouldn't be bound tightly with other tools. However, regarding the ideas I previously mentioned, I don't think they are specific to `direnv`. What are your thoughts on them?
> 
> If you don't have time to implement them at the moment, I am also willing to contribute and work on them, if you would like.

Sorry, my bad. I thought I had pushed the branch but actually I hadn't.  :(

Just pushed. You can try it now.

**Comment by WeissP** [comment] 2024-07-27 10:45
Hi, yes, now it works as expected! Thanks!

**Comment by zbelial** [comment] 2024-07-27 10:48
Great! Thanks for testing it. 
If you have other problems, open new issues please.

**Closed by zbelial** 2024-07-27 10:48 UTC
